### PR TITLE
refactor: Upgrade expo version and dependencies

### PR DESCRIPTION
**Pull request by theolampert**

### CODE REVIEW

**Review by simison — APPROVED** [review]
Tested locally on iphone simulator, works great 👍 

Feel free to merge.

**Comment by simison** [comment]
There's this warning in console likely due React version upgrade, would be easy to address here (just by renaming) — but ok to address in follow-ups too:

```
 WARN  Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: App
```

**Comment by theolampert** [comment]
@simison yeah I can take care of that in this PR

**Comment by theolampert** [comment]
@simison this has been updated now.

**Review by simison — APPROVED** [review]
👍

**Pull request merged**
